### ISSUE TITLE
Suggestion: Minimal Blazor wasm example

### ISSUE THREAD

**Issue by srcmkr** [servicetitan/Stl.Fusion.Samples#18]
I think it would be very helpful to have a minimal blazor wasm example.
Pages to cover: /counter and /weatherforecast (both with EFCore)
So: No specials (even custom logging), just the default wasm boilerplate with a minimal implementation of Stl.Fusion

The documentation and samples give a very deep insight, which might be too much to see how easy the implementation really can be.

**Comment by seertenedos** [comment]
With Auth as well. i have been struggling to get a wasm dotnet 6 blazor example working. I took the existing blazor one and tried to apply most of it to new dotnet 6 Wasm blazor app but i have not managed to get it fully working yet and it has been quite a bit of work.  Server side Blazor is easier i think but because all the samples mix serverside and wasm blazor together it make sit hard to work out what parts are server side and not needed for client side blazor and which parts need to be moved to a different location to work in a default wasm blazor app

**Comment by alexyakunin** [comment]
@seertenedos check out https://github.com/alexyakunin/FusionQA/tree/main/FusionQA.Mar2022 - this is probably what you're looking for
